[#176884219] Add orchestrator's ERROR status management
pagopa/io-functions-cgn pull request #28
Opened 2021-02-24 17:21 UTC by AleDore

#### List of Changes
- Add `ERROR` custom status on orchestrators
- Add ERROR status mapping on `GetCgnActivation`
- Add ERROR status mapping on `GetEycaActivation`
- Small refactor on orchestrator's utility

#### Motivation and Context
Since an orchestrator update/activation process of CGN or EYCA Card could fail while attempting max number of retries, we must manage a custom error status that could match with the effective status of the orchestrator. This status is used as well in HTTP handler called by client to know the status of the activation processes either of CGN an EYCA Card.
BTW `RuntimeStatus` cannot be used as a "source of truth" since it maps a completed execution when the durable function fails over the max number of attempts on retry logic. 

#### How Has This Been Tested?
It has been tested by performing unit and integration tests .

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2021-02-25 10:33 UTC, AleDore commented on UpdateCgnOrchestrator/index.ts
>      if (newStatusCard.status === ActivatedStatusEnum.ACTIVATED) {
This branch is in a fire&forget logic, so it will not set `ERROR` custom status if it fails :)

2021-02-25 10:50 UTC, balanza commented on utils/orchestrators.ts
> +  throw new Error(String(err));
What's the outcome of `String(err)` when type of `err` is `t.Errors`? Anyway, I'd rather spend a line of code and be more explicit:
```ts
const errMessage = err instanceOf Error ? err.message : readableReport(err);
throw new Error(errMessage);
```

2021-02-25 10:50 UTC, balanza commented on utils/orchestrators.ts
> +  throw new Error(String(err));
(I see you actually did it just above)

2021-02-25 10:50 UTC, balanza commented on utils/orchestrators.ts
> +  throw new Error(String(err));
ditto

2021-02-25 10:50 UTC, balanza commented on utils/orchestrators.ts
> +export const trackEventIfNotReplaying = (
Can you add a comment explaining the function?

2021-02-25 10:50 UTC, balanza commented on utils/orchestrators.ts
> +export const trackExceptionIfNotReplaying = (
Can you add a comment explaining the function?

2021-02-26 16:23 UTC, BurnedMarshal requested changes

2021-03-01 10:03 UTC, BurnedMarshal approved these changes
LGTM

2021-03-01 10:19 UTC, merged