[#177116784] Add Redis config
pagopa/io-functions-cgn pull request #30
Opened 2021-02-26 17:10 UTC by AleDore

#### List of Changes
- Add Redis configuration and client
- Update dependencies and typings

#### Motivation and Context
Since CGN must provide a One Time Password, to be used through online purchase, we must store this temporary data in a proper cache. This will be used also for other optimizations.

#### How Has This Been Tested?
No tests needed.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2021-03-01 11:15 UTC, BurnedMarshal requested changes

2021-03-01 11:15 UTC, BurnedMarshal commented on utils/config.ts
> +    REDIS_CLUSTER_ENABLED: t.boolean,
If we have this tyings, we need to remap the value in [here](https://github.com/pagopa/io-functions-cgn/pull/30/files#diff-8f4625a1cf4cb245a2f9e780a9a17ff6a7132b8e070997144a67499d7ff793b4R48)
like
```typescript
const errorOrConfig: t.Validation<IConfig> = IConfig.decode({
  ...process.env,
  isProduction: process.env.NODE_ENV === "production",
  REDIS_CLUSTER_ENABLED: fromNullable(process.env.REDIS_CLUSTER_ENABLED)
    .map(_ => _.toLowerCase() === "true")
    .toUndefined()
});
```

2021-03-01 11:15 UTC, BurnedMarshal commented on utils/redis.ts
> +      );
If you like it we can remove the if and use `fromPredicate` instead.
```suggestion
export const REDIS_CLIENT = fromPredicate<boolean>(_ => _)(config.isProduction)
  .mapNullable(_ => config.REDIS_CLUSTER_ENABLED)
  .chain(fromPredicate(_ => _))
  .map(() =>
    createClusterRedisClient(
      config.REDIS_URL,
      config.REDIS_PASSWORD,
      config.REDIS_PORT
    )
  )
  .getOrElseL(() =>
    createSimpleRedisClient(
      config.REDIS_URL,
      config.REDIS_PASSWORD,
      config.REDIS_PORT,
      true
    )
  );
```

2021-03-02 08:22 UTC, BurnedMarshal approved these changes
LGTM apart the missing envs into`env.example`

2021-03-02 08:22 UTC, BurnedMarshal commented on utils/config.ts
> +    REDIS_PORT: NonEmptyString
Could you add this ENVs inside the `env.example` file? We should upgrade even `io-mock` configuration for `fn-cgn`

2021-03-02 15:33 UTC, AleDore commented
> Could you add this ENVs inside the `env.example` file? We should upgrade even `io-mock` configuration for `fn-cgn` 

Done -> [https://github.com/pagopa/io-mock/pull/31](https://github.com/pagopa/io-mock/pull/31) :)

2021-03-02 16:52 UTC, merged