[#IC-178] Add special service integration on activation
pagopa/io-functions-cgn pull request #62
Opened 2022-01-11 14:52 UTC by AleDore

#### List of Changes

#### Motivation and Context

This is required since CGN is a special service so it must be addressed and managed with special service activation
#### How Has This Been Tested?

Unit test
#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2022-01-12 13:54 UTC, michaeldisaro approved these changes
LFTM

2022-01-12 14:37 UTC, BurnedMarshal commented on UpdateCgnOrchestrator/handler.ts
> +        }
What do you think about this more functional version?
```suggestion
        pipe(
          yield context.df.callActivityWithRetry(
            "UpsertSpecialServiceActivationActivity",
            internalRetryOptions,
            upsertSpecialServiceActiveActivityInput
          ),
          ActivityResult.decode,
          E.getOrElseW(e =>
            trackExAndThrowWithError(
              e,
              "cgn.update.exception.upsertSpecialServiceActive.activityOutput"
            )
          ),
          E.fromPredicate(
            _ => _.kind === "SUCCESS",
            () =>
              trackExAndThrowWithError(
                new Error("Cannot upsert CGN Special service activation"),
                "cgn.update.exception.failure.upsertSpecialService.activityOutput"
              )
          )
        );
```

2022-01-12 14:37 UTC, BurnedMarshal commented on clients/services.ts
> +export const cgnSubscriptionKey = config.SERVICES_API_KEY;
This variables are exported but are used locally. Maybe we can use directly `config.SERVICES_API_...` or use a local const not exported.

2022-01-12 14:37 UTC, BurnedMarshal commented on clients/services.ts
> +const DEFAULT_REQUEST_TIMEOUT_MS = 10000;
10 seconds, fix the comment

2022-01-12 14:37 UTC, BurnedMarshal commented on package.json
> +    "generate:api-services": "shx rm -rf generated/services-api && gen-api-models --api-spec https://raw.githubusercontent.com/pagopa/io-functions-services/master/openapi/index.yaml --no-strict --out
Should we use a specific `fn-services` version specification instead of `master`?

2022-01-12 14:37 UTC, BurnedMarshal commented on UpsertSpecialServiceActivationActivity/handler.ts
> +          err => fail(err, "Cannot upsert special service activation"),
With this fail we cannot retry the Activity if `upsertServiceActivation` fail. Should this maybe become a throw?

2022-01-12 14:47 UTC, BurnedMarshal requested changes

2022-01-12 14:47 UTC, BurnedMarshal commented on UpdateCgnOrchestrator/__tests__/handler.test.ts
> +    );
this can be removed :D

2022-01-12 14:47 UTC, BurnedMarshal commented on UpsertSpecialServiceActivationActivity/__tests__/handler.test.ts
> +  });
This type of error should return an exception, not an Activity permanent failure. (related to the comment inside the `handler.ts`)

2022-01-12 14:47 UTC, BurnedMarshal commented on UpsertSpecialServiceActivationActivity/__tests__/handler.test.ts
> +    ${"Unhandled Error"}       | ${{ status: 599 }}
Should some of this errors trigger the Activity retry? For sure at least 429 and 500, open point for the others responses status code.

2022-01-14 08:59 UTC, michaeldisaro approved these changes

2022-01-14 09:33 UTC, BurnedMarshal requested changes

2022-01-14 09:33 UTC, BurnedMarshal commented on UpsertSpecialServiceActivationActivity/__tests__/handler.test.ts
> +      TE.mapLeft(ex => expect(ex).toBeDefined())
Always test both the side of the TE. For example : 
```suggestion
      TE.bimap(
        ex => expect(ex).toBeDefined(),
        _ => fail("Unexpected value")
      )
```
But something is wrong in here. A wrong input decode should return a permanent failure not a transient one with related throw of the Activity 🤔

2022-01-14 09:33 UTC, BurnedMarshal commented on UpsertSpecialServiceActivationActivity/handler.ts
> +        return err;
Permanent failure should return and transient should throw.
```suggestion
        if (TransientFailure.is(err)) {
          throw new Error(err.reason);
        }
        return err;
```

2022-01-14 14:18 UTC, BurnedMarshal approved these changes
LGTM

2022-01-14 17:53 UTC, merged